persistentStorage:
  persistentStoreType: gcs
  gcs:
    jsonPath: /my/file
    project: spinnaker
    bucket: my-bucket
    rootFolder: front50
    bucketLocation: us
providers:
  kubernetes:
    enabled: true
    accounts:
    - name: prod-demo-1
      requiredGroupMembership: []
      providerVersion: 1
      permissions: {}
      dockerRegistries: []
      context: my-context
      configureImagePullSecrets: true
      cacheThreads: 1
      namespaces: []
      omitNamespaces: []
      kinds:
        - replicaSet
        - deployment
      omitKinds:
        - cronTab
      customResources: []
      cachingPolicies: []
      kubeconfigFile: /my/kube/config
      oauthScopes: []
